7340 - Init script improvements
Use builtin RC functions for starting, stopping and checking status of daemon

- No longer restarts existing daemon when called with "start".
- Should hopefully alleviate issues of multiple daemons running.
- Some minor tidying.
- Backwards compatible with EL<5.
- Needs testing against LSB before changes are merged to "mcollective.init".
- Correct mixed whitespace. Standardised to 4 space indents.

Signed-off-by: R.I.Pienaar <rip@devco.net>

diff --git a/mcollective.init b/mcollective.init
--- a/mcollective.init
+++ b/mcollective.init
@@ -1,12 +1,12 @@
 #!/bin/sh
 #
-# mcollective	Application Server for STOMP based agents
+# mcollective   Application Server for STOMP based agents
 #
-# chkconfig: 345 24 76
+# chkconfig:    345 24 76
 #
-# description: mcollective lets you build powerful Stomp compatible middleware clients in ruby without having to worry too
-#              much about all the setup and management of a Stomp connection, it also provides stats, logging and so forth
-#              as a bonus.
+# description:  mcollective lets you build powerful Stomp compatible middleware clients in ruby without having to worry too
+#               much about all the setup and management of a Stomp connection, it also provides stats, logging and so forth
+#               as a bonus.
 #
 ### BEGIN INIT INFO
 # Provides:          mcollective
@@ -25,11 +25,11 @@ mcollectived="/usr/sbin/mcollectived"
 
 # Lockfile
 if [ -d /var/lock/subsys ]; then
-  # RedHat/CentOS/etc who use subsys
-  lock="/var/lock/subsys/mcollective"
+    # RedHat/CentOS/etc who use subsys
+    lock="/var/lock/subsys/mcollective"
 else
-  # The rest of them
-  lock="/var/lock/mcollective"
+    # The rest of them
+    lock="/var/lock/mcollective"
 fi
 
 
@@ -40,86 +40,88 @@ pidfile="/var/run/mcollectived.pid"
 . /lib/lsb/init-functions
 
 # Check that binary exists
-if ! [ -f  $mcollectived ]
+if ! [ -f $mcollectived ]
 then
-  echo "mcollectived binary not found"
-  exit 0
+    echo "mcollectived binary not found"
+    exit 0
 fi
 
 # See how we were called.
 case "$1" in
-  start)
-	echo -n "Starting mcollective: "
+    start)
+        echo -n "Starting mcollective: "
 
-	if [ -f ${lock} ]; then
-	    # we were not shut down correctly
-	    if [ -s ${pidfile} ]; then
-		kill `cat ${pidfile}` >/dev/null 2>&1
-	    fi
-	    rm -f ${pidfile}
+        if [ -f ${lock} ]; then
+            # we were not shut down correctly
+            if [ -s ${pidfile} ]; then
+                kill `cat ${pidfile}` >/dev/null 2>&1
+            fi
+            rm -f ${pidfile}
 
-	    rm -f ${lock}
-	    sleep 2
-	fi
+            rm -f ${lock}
+            sleep 2
+        fi
 
-	rm -f ${pidfile}
+        rm -f ${pidfile}
 
-	${mcollectived} --pid=${pidfile} --config="/etc/mcollective/server.cfg"
-	if [ $? = 0 ]; then
-	    log_success_msg
-	    touch $lock
-	    exit 0
-	else
-	    log_failure_msg
+        ${mcollectived} --pid=${pidfile} --config="/etc/mcollective/server.cfg"
+        if [ $? = 0 ]; then
+            success $"mcollectived"
+            touch $lock
+            echo
+            exit 0
+        else
+            failure
+            echo
             exit 1
-	fi
-	;;
-  stop)
-	echo -n "Shutting down mcollective: "
+        fi
+        ;;
+    stop)
+        echo -n "Shutting down mcollective: "
 
-	if [ -s ${pidfile} ]; then
-	  kill `cat ${pidfile}` >/dev/null 2>&1
-	fi
-	rm -f ${pidfile}
+        if [ -s ${pidfile} ]; then
+            kill `cat ${pidfile}` >/dev/null 2>&1
+        fi
+        rm -f ${pidfile}
 
-	log_success_msg
-	rm -f $lock
-	;;
-  restart)
-	$0 stop
-	sleep 2
-	$0 start
-	;;
-  condrestart)
-	if [ -f $lock ]; then
-	    $0 stop
-	    # avoid race
-	    sleep 2
-	    $0 start
-	fi
-	;;
-  status)
-	if [ -f ${lock} ]; then
-	    if [ -s ${pidfile} ]; then
-	       if [ -e /proc/`cat ${pidfile}` ]; then
-                  echo "mcollectived (`cat ${pidfile}`) is running"
-                  exit 0
-               else
-                  echo "mcollectived (`cat ${pidfile}`) is NOT running"
-                  exit 1
-               fi
-	    fi
-	else
-	    echo "mcollectived: service not started"
-	    exit 1
-	fi
-  ;;
-	force-reload)
-		echo "not implemented"
-	;;
-  *)
-	echo "Usage: mcollectived {start|stop|restart|condrestart|status}"
-	exit 1
-	;;
+        log_success_msg
+        rm -f $lock
+        ;;
+    restart)
+        $0 stop
+        sleep 2
+        $0 start
+        ;;
+    condrestart)
+        if [ -f $lock ]; then
+            $0 stop
+            # avoid race
+            sleep 2
+            $0 start
+        fi
+        ;;
+    status)
+        if [ -f ${lock} ]; then
+            if [ -s ${pidfile} ]; then
+                if [ -e /proc/`cat ${pidfile}` ]; then
+                    echo "mcollectived (`cat ${pidfile}`) is running"
+                    exit 0
+                else
+                    echo "mcollectived (`cat ${pidfile}`) is NOT running"
+                    exit 1
+                fi
+            fi
+        else
+            echo "mcollectived: service not started"
+            exit 1
+        fi
+        ;;
+    force-reload)
+        echo "not implemented"
+        ;;
+    *)
+        echo "Usage: mcollectived {start|stop|restart|condrestart|status}"
+        exit 1
+        ;;
 esac
 exit 0
